name: Javadoc
on:
  push:
    branches:
      - master
jobs:
  javadoc:
    name: Generate Javadoc in /docs
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Generate javadoc
      run: ./gradlew javadoc
    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs # The folder the action should deploy.
